variables:
  COVERALLS_DEBUG: true
  COVERALLS_ENDPOINT: https://ce93d152.ngrok.io

before_script:
  - gem install bundler --no-ri --no-rdoc
  - bundle install --jobs $(nproc)  "${FLAGS[@]}"

spec:one:
  script:
    - bundle exec rspec spec/run_spec.rb

spec:two:
  script:
    - bundle exec rspec spec/run2_spec.rb
