before_script:
  - gem install bundler --no-ri --no-rdoc
  - bundle install --jobs $(nproc)  "${FLAGS[@]}"

rspec:
  script:
    - COVERALLS_DEBUG=true COVERALLS_ENDPOINT=https://ce93d152.ngrok.io COVERALLS_REPO_TOKEN=TxIFh4oVfsWlLxT94TaHdGmDh01pR30fI bundle exec rspec
